# 配置优先级：由高到低
# 既有application.yml也有application.properties，默认先读取application.properties
# 0、启动命令行上
# Java 系统属性
# 操作系统环境变量
# 1、config/application.properties（项目根目录中config目录下）
# 2、config/application.yml
# 3、application.properties（项目根目录下）
# 4、application.yml
# 5、resources/config/application.properties（项目resources目录中config目录下）
# 6、resources/config/application.yml
# 7、resources/application.properties（项目的resources目录下）
# 8、resources/application.yml
# SpringBoot项目时，一般的配置文件放置在“项目的resources目录下
